name: Check amendment annotations on substantive changes to Rec
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  check-amendment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./tools/check-rec-amendment.js')
            await script({github, context, core})
